from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DEFAULT_CONFIG = ROOT / "configs" / "base.yaml"
CALIBRATION_FILE = ROOT / "configs" / "calibration.yaml"


def _merge(base, override):
    for k, v in override.items():
        if isinstance(v, dict) and isinstance(base.get(k), dict):
            _merge(base[k], v)
        else:
            base[k] = v
    return base


def load_config(path=DEFAULT_CONFIG, use_calibration=True):
    """Load the hand-written config, then overlay values produced by calibration scripts."""
    with open(path, "r", encoding="utf-8") as f:
        cfg = yaml.safe_load(f)
    if use_calibration and CALIBRATION_FILE.exists():
        with open(CALIBRATION_FILE, "r", encoding="utf-8") as f:
            _merge(cfg, yaml.safe_load(f) or {})
    return cfg


def save_calibration(values):
    """Merge `values` (nested dict) into configs/calibration.yaml."""
    current = {}
    if CALIBRATION_FILE.exists():
        with open(CALIBRATION_FILE, "r", encoding="utf-8") as f:
            current = yaml.safe_load(f) or {}
    with open(CALIBRATION_FILE, "w", encoding="utf-8") as f:
        f.write("# Auto-generated by calibration scripts. Do not edit by hand.\n")
        yaml.safe_dump(_merge(current, values), f, sort_keys=False)


def density_lambdas(cfg):
    """Arrival rate (veh/s) for each named density level."""
    lam_max = cfg["demand"]["lambda_max"]
    if lam_max is None:
        raise RuntimeError("lambda_max not calibrated; run: python -m experiments.calibrate_density")
    return {k: round(f * lam_max, 3) for k, f in cfg["demand"]["density_levels"].items()}
